config/routes.rb
Rails.application.routes.draw do
  resource :account, only: [:show]

  resources :repairs do
    post "update_saver" => "repairs#update_saver"
    post "update_status" => "repairs#update_status"
  end
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get "solution" => "pages#solution"
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create]
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :problems, class_name: 'Repair', foreign_key: 'client_id'
  has_many :missions, class_name: 'Repair', foreign_key: 'saver_id'
  has_many :reviews
  has_attachment :photo
  validates :first_name, presence: true
  #validates :phone, format: { with: /\A((\+|00)33\s?|0)[1-9](\s?\d{2}){4}\Z/,
  #                             message: "wrong phone number format"}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @savers = User.where(saver: true)
  end

  def show
    @saver = User.find(params[:id])
    @review = Review.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="dashboard-container">
  <div class="container">
    <div class="row">
    <h1 class="text-center dashboard-h1">All the Savers</h1>
      <% @savers.each do |saver| %>
        <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-0">
          <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= ENV["BASE_DELIVERY_URL"]+'/image/upload/'+saver.photo.path %>');">
            <div class="card-category"></div>
            <div class="card-description">
              <h2><%= saver.first_name %></h2>
            </div>
            <%= link_to "", user_path(saver), class: "card-link" %>
          </div>
        </div>
      <% end %>
      <br></br>
    </div>
  </div>
</div>
<div class= "text-center">
<%= link_to "get back to my profil", account_path, class: "btn btn-brand" %>
</div>

app/views/users/reparator_index.html.erb
<div class="dashboard-container">
  <h1 class="text-center reparator-h1">All the reparators</h1>
    <div class="dashboard-tab">
       <div>

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Laure</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Cyril</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Matthias</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active tab-content-padding" id="home">...</div>
        <div role="tabpanel" class="tab-pane tab-content-padding" id="profile">...</div>
        <div role="tabpanel" class="tab-pane tab-content-padding" id="messages">...</div>
      </div>

    </div>
  </div>
</div>



<div class="container">
    <div class="row">
        <%@reparators.each do |reparator|%>
      <div class="col-xs-12 col-md-4">
        <%=reparator.first_name%>
      </div>
        <%end%>
    </div>
  </div>

app/views/users/show.html.erb
<div class="dashboard-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <h1 class="text-center dashboard-h1"><%= @saver.first_name %></h1>
        <!-- carte de profil -->
      </div>
      <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
        <div id="reviews">
            <% if @saver.reviews.blank? %>
              Be the first to leave a review for <%= @saver.first_name %>
            <% else %>
              <% @saver.reviews.each do |review| %>
                <%= render 'reviews/show', review: review %>
              <% end %>
            <% end %>
        </div>
        <div class="review-form">
          <%= render 'reviews/formreview', saver: @saver, review: @review %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/showsaver.html.erb
<div class="dashboard-container">

  <h1 class="text-center dashboard-h1">Dashboard</h1>
  <div class="dashboard-tab">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab" class="tab-width"><i class="fa fa-home"></i>  Pending</a></li>
      <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab" class="tab-width allocated"><i class="fa fa-clock-o"></i>  Allocated to me</a></li>
      <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab" class="tab-width"><i class="fa fa-check"></i>  Done</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active tab-content-padding" id="home">
          <%@repairs_saver_nil.each do |repair|%>
              <ul class="list-unstyled">
                <li class = "dashboard-li-padding">
                  <strong><%=repair.category.capitalize%></strong>
                  <%=repair.address%>
                  <%=repair.id%>
                  <%=repair.created_at.time%>
                  <p><strong>First Name: </strong><%=repair.client.first_name%></p>
                  <p><strong>Phone: </strong><%=repair.client.phone%></p>
                  <%= form_tag repair_update_saver_path(repair) do %>
                    <%= hidden_field_tag :saver_id, current_user.id  %>
                    <%= submit_tag "I handle it!", class: "btn btn-success btn-handle" %>
                  <% end %>
                </li>
              </ul>
          <%end%>
      </div>
      <div role="tabpanel" class="tab-pane tab-content-padding" id="profile">
        <%current_user.missions.where(status: "draft").each do |mission|%>
        <ul class="list-unstyled">
          <li class = "dashboard-li-padding">
            <strong><%=mission.category.capitalize%></strong>
            <%=mission.address%>
              <%= form_tag repair_update_status_path(mission) do %>
                <%= hidden_field_tag :status, mission.status = "done" %>
                <%= submit_tag "Done !", class: "btn btn-success btn-handle handle" %>
              <% end %>
          </li>
        </ul>
        <%end%>
      </div>
      <div role="tabpanel" class="tab-pane tab-content-padding" id="messages">
        <%current_user.missions.where(status: "done").each do |mission| %>
        <ul class="list-unstyled">
          <li>
            <i class="fa fa-check"></i>
            <strong><%=mission.category.capitalize%></strong>
            <%=mission.address%>
            <%=mission.status %>
          </li>
        </ul>
        <%end%>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {
    $(".handle").on("submit", function(event) {


    return false; // prevent it from being submitted (errors, etc.)
});
  });
</script>