config/routes.rb
Rails.application.routes.draw do
  resource :account, only: [:show]

  resources :repairs do
    post "update_saver" => "repairs#update_saver"
    post "update_status" => "repairs#update_status"
  end
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get "solution" => "pages#solution"
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create]
  end

  mount Attachinary::Engine => "/attachinary"

end

app/views/pages/home.html.erb
<section class="cd-intro">
  <div class="cd-intro-content bouncy">
    <div class="background-home">
      <div class="gradient">
        <div class="content text-center">
          <h1>An angel fixes your bike in 30 minutes!</h1>
          <p style="font-size: 150%;">Flat tyre? Broken chain? We come to fix it everywhere in London!</p>
            <%= form_tag(new_repair_path, method: :get, class: "form-inline form-home") do %>
              <%= text_field_tag :address, nil, class: "form-control", placeholder: "Address", id: "user_input_autocomplete_address"%>
              <%= text_field_tag :postal_code, nil, class: "form-control", id: "postal_code", :type => "hidden"%>
              <%= submit_tag "Rescue me now!", class: "btn btn-brand"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>




  <div class="home-wrapper">

      <div class="row">
         <h1 class="text-center">
         <div class="fancy-underlined step1">
            How to?
          </div>
          </h1>
            <div class="col-xs-12 col-sm-4 card-feature">
              <%= image_tag('FTI.png') %>
            <p class="text-center zone-text">Flate tyre? Worn brakes? Broken chain? Just give us your address and phone number</p>
          </div>
        <div class="col-xs-12 col-sm-4 card-feature">
          <%= image_tag('logo.png') %>
            <p class="text-center zone-text"> We call you back immediatly and send an angel to the rescue in less than 30 minutes</p>
          </div>
        <div class="col-xs-12 col-sm-4 card-feature2">
        <%= image_tag('bikepoint.png') %>
            <p class="text-center zone-text">Your bike is fixed, you can finish your ride!</p>
        </div>
      </div>

  </div>

  <div class="home-wrapper">
      <div class="row">
         <h1 class="text-center" style="margin-bottom: 40px">
         <div class="fancy-underlined step2">
         They will soon talk about us!
         </div></h1>
        <div class="col-xs-4 col-sm-2 press-logo">
          <%= image_tag('les-inrocks.jpg') %>
        </div>
        <div class="col-xs-4 col-sm-2 press-logo">
        <%= link_to image_tag('le-parisien.png') %>
        </div>
        <div class="col-xs-4 col-sm-2 press-logo">
        <%= link_to image_tag('logo20minutes.png') %>
        </div>
        <div class="col-xs-4 col-sm-2 press-logo">
        <%= link_to image_tag('Elle-logo.jpg') %>
      </div>
      <div class="col-xs-4 col-sm-2 press-logo">
      <%= link_to image_tag('konbini.png') %>
      </div>
      <div class="col-xs-4 col-sm-2 press-logo">
      <%= link_to image_tag('festival.png') %>
      </div>
    </div>
  </div>