config/routes.rb
Rails.application.routes.draw do
  resource :account, only: [:show]

  resources :repairs do
    post "update_saver" => "repairs#update_saver"
    post "update_status" => "repairs#update_status"
  end
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get "solution" => "pages#solution"
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create]
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  # mount_uploader :photo, PhotoUploader
  CATEGORIES = ["flat tyre", "worn brakes", "broken chain"]
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :client, class_name: 'User', foreign_key: 'client_id'
  belongs_to :saver, class_name: 'User', foreign_key: 'saver_id'
  has_attachment :photo
  validates :client_id, presence: true
  validates :category, inclusion: {in: CATEGORIES}, presence: true

end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :new, :destroy]
  before_action :set_repair, only: [:show, :edit, :update, :update_saver,:update_status, :destroy]



  def index
    @repairs = Repair.all
    @markers = Gmaps4rails.build_markers(@repairs) do |repair, marker|
      marker.lat repair.latitude
      marker.lng repair.longitude
    end
  end

  def show
    @repair_coordinates = { latitude: @repair.latitude, longitude: @repair.longitude }
    @markers = Gmaps4rails.build_markers(@repair) do |repair, marker|
      marker.lat repair.latitude
      marker.lng repair.longitude
    end
  end

  def create
    @repair = Repair.new(repair_params)
    @repair.client_id = current_user.id
    @repair.phone = current_user.phone
    if @repair.save
      #to send sms decomment the line below
      send_sms_to_saver
      redirect_to repair_path(@repair)
    else
      render :new
    end
  end

  def new
    @repair = Repair.new
    @current_user = current_user
    @address= params[:address]
    @category= params[:category] || session[:category_before_register]
    @photo = params[:photo]
    @photo_cache = params[:photo_cache]
    @client_id= @current_user_id

  end

  def edit
  end

  def update
    @repair.assign_attributes(repair_params)

    if @repair.phone_changed?
      current_user.phone = @repair.phone
    end

    @repair.save
    current_user.save if current_user.changed?

    redirect_to repair_path(@repair)
  end

  def update_saver
    @repair.saver_id = params[:saver_id]
    @repair.save


    Pusher.trigger("repair-#{@repair.id}", "my_event", {:repair_man => @repair.saver.first_name})
    # this path below if for the saver = when he decide to handle a reparation, the redirect is in the dashboard
    redirect_to account_path
  end

  def update_status
    @repair.status = params[:status]
    @repair.save
    # this path below if for the saver = when he decide to handle a reparation, the redirect is in the dashboard
    redirect_to account_path
  end

  def destroy
    @repair.delete
    # redirect_to destroy_user_session_path, method: :delete

  end

private

  def set_repair
    @repair = Repair.find(params[:id] || params[:repair_id])
  end

  def repair_params
    params.require(:repair).permit(:status, :category, :address, :client_id, :saver_id, :photo, :photo_cache, :phone, :description)
  end

  def send_sms_to_saver

    require 'rubygems'
    require 'twilio-ruby'

    # Get your Account Sid and Auth Token from twilio.com/user/account
    account_sid = 'AC8061fb151ba03fdd3e78e5c42fec5f45'
    auth_token = 'f10fd2a4bfde7d1e232b0e029ae4dca2'
    @client = Twilio::REST::Client.new account_sid, auth_token

    savers = {
      "laure" => "+33613026359",
      "matthias" => "+33688833732",
      "cyril" => "+33662549166"
    }

    savers.each do |saver, phone|
      message = @client.account.messages.create(:body => "Une nouvelle requette est créée! Rendez-vous sur www.bikeangels.fr/account",
          :to => phone,     # Replace with your phone number
          :from => "+33756796785")   # Replace with your Twilio number
      puts message.sid
    end
  end

end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/create.html.erb
<h1>Repairs#create</h1>
<p>Find me in app/views/repairs/create.html.erb</p>

app/views/repairs/destroy.html.erb
<<% content_for(:title) do %> You are deleting your order:
  <%= @repair.address %>
<% end %>

<!-- displaying the image of the home page via Cloudinary -->

<div class='banner-bike baner' >

</div>
<br></br>
<br></br>
<div class= "container">
<h2> Goodbye <%= @repair.client.first_name %>! </h2>
<p> Thanks for visiting us!</p>
<br></br>
<%= link_to "ok", repairs_path, class: "btn btn-brand" %>
</div>

app/views/repairs/edit.html.erb
<div class="background">
    <div class="bg-gradient flex">
      <div class="form-group">
        <div class="container">
          <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
              <div class="background-white">
              <%= simple_form_for(@repair) do |f| %>
              <div class="form-for">
              <%= f.error_notification %>
              <h3> <i class="fa fa-bicycle"></i> Whant to change your adress? <i class="fa fa-bicycle"></i> <h3>
      <!-- Get the address from home page -->
              <%= f.input :address, label: false %>
      <!-- displaying the category of repair-->
              <h3> Made an error concerning the issue? </h3>
              <%=f.input :category, as: :select, label: false, collection: Repair::CATEGORIES, :include_blank => false %>
              <h3> Or concerning your phone number? </h3>
              <%= f.input :phone %>
              <%= f.button :submit, "Go!", class: "btn btn-brand btn-full-width" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/repairs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 ">
         <div id="map" style="width: 100%; height: 300px;">
        </div>
    </div>
  </div>
</div>

<div class="wrapper-grey padded">
  <div class="container">
    <h2 class="text-center">All Repairs</h2>
    <div class="row">
      <% @repairs.each do |repair| %>

        <% if repair.category == "flat tire" %>
        <% photo_repair = image_path('pneu.jpg')  %>
        <% elsif repair.category == "worn brakes" %>
        <% photo_repair = image_path('freins.jpg')  %>
        <% elsif repair.category == "broken chain" %>
        <% photo_repair = image_path('chaine.jpg')  %>
        <% else  photo_repair == image_path('chaine.jpg') %>
        <% end %>

      <div class="col-xs-12 col-sm-4">
        <div class="card2" style="background: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0)), url(<%=  photo_repair %>);">
          <div class="card-category"><%= repair.address %></div>
            <div class="card-description">
              <h2><%= repair.category %></h2>
            </div>
            <%= link_to "", repair_path(repair), class: "card-link" %>
            <!-- <a class="card-link" href="#" ></a> -->
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
  <% end %>

app/views/repairs/new.html.erb
<!-- displaying the title of the page on the navigation bar -->
<% content_for(:title) do %> Your are
<%= @repair.address %>
<% end %>

<!-- displaying the image of the home page via Cloudinary -->
<div class='banner-bike'>

</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="new-repair-container">
        <h1>Tell us about your situation</h1>
        <P>Leave us your details</P>
        <!-- displaying the new form -->
        <%= simple_form_for(@repair, class: "mon_form") do |f| %>

        <div class="form-for">
          <%= f.error_notification %>
          <h3> <i class="fa fa-bicycle"></i> You are here: <i class="fa fa-bicycle"></i> <h3>
            <!-- Get the address from home page -->
            <%= f.input :address, label: false, input_html: {value: @address} %>
            <!-- displaying the category of repair-->
            <h3> Pick your issue in the list </h3>
            <%= f.input :category, as: :select, label: false, collection: Repair::CATEGORIES, :include_blank => true, selected: @category %>
            <!-- displaying the prices of repairs -->
            <div class="row text-center icons-row">
              <div class="col-xs-6 col-sm-3 col-md-2"><P>tyre</P>
                <%= image_tag "tire.png", height: '40' %>
                <p> 15 € </p>
              </div>
              <div class="col-xs-6 col-sm-3 col-md-2"><p>brakes</p>
                <%= image_tag "brake2.png", height: '40' %>
                <p> 20 € </p>
              </div>
              <div class="col-xs-6 col-sm-3 col-md-2"><p>chain</p>
                <%= image_tag "chain2.png", height: '40' %>
                <p> 20 €</p>
              </div>
            </div>
          </div>
          <!-- Adding a description and a photo if the choice is not on the list -->
          <% if user_signed_in? %>
          <a data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <p> Click here if your problem is not on the list</p>
          </a>
          <div class="collapse" id="collapseExample">
            <div class="well">
              <p>Send us a photo with your phone or leave us a description. We will see if we can handle it! </>
                <% #if user_signed_in? %>
                <%= f.input :description, placeholder: "Leave a comment about your issue" %>
<!--                 <%= #f.input :photo, as: :attachinary %> -->
              </div>
            </div>
          <% end %>
          <br></br>
            <!-- add a description to repair-->

            <!-- Different view if the client is signed up or not -->
            <% if @current_user %>
            <%= f.submit " Click here for a rescue!", class: "btn btn-danger" %>
            <% else %>
            <%= link_to 'Order a rescue!',  new_user_registration_path, class: "btn btn-brand btn-full-width cd-btn main-action"%>
            <% end%>

          </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>

app/views/repairs/show.html.erb
<!-- displaying the title of the page on the navigation bar -->
<% content_for(:title) do %> Your are
  <%= @repair.address %>
<% end %>

<!-- displaying the image of the home page via Cloudinary -->

<div class='banner-bike baner' ></div>

<div class="container container-fluid client-view">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-5 col-md-offset-1">
      <div class="">
          <div class="col-sm-2 col-xs-hidden">

          </div>

          <div class="col-sm-10 text-justify repair-client-name">
<!-- displaying the name of the client -->
             <h1><strong>Hello <%= @repair.client.first_name %>! </strong> </h1>
             <p>Thanks for calling us </p>
             <div id="repair_man", class ="repair_man_name"></div>
          </div>

<!-- displaying the category of the client's problem -->
      <div class="">
        <ul class="list-unstyled align">
          <li>
            <span>You have a <strong><%= @repair.category %> </strong>?<span/>
          </li>
          <li>
             <% if @repair.category == "flat tire" %>
           <%= image_tag "tire.png", height: '30' %>
            <% elsif @repair.category == "worn brakes" %>
           <%= image_tag "brake2.png", height: '30' %>
            <% elsif @repair.category == "broken chain" %>
           <%= image_tag "chain2.png", height: '30' %>
            <% end %>
          </li>
        </ul>



  <!-- displaying the phone of the client -->
            <p> Don't worry! One of our <strong>saver</strong> will come to help you!</p>
            <p> You will be called soon at <strong><%= @repair.client.phone.gsub(/\s+/, "").gsub(/^\+?33/, "0").gsub(/(.{2})(?=.)/, '\1 \2') %> </strong></p>
            <p> The price of our intervention is:
  <!-- displaying the prices of the repairs -->
          <% if @repair.category == "flat tyre" %>
         <P> <strong>15 euros</strong> </P>
          <% elsif @repair.category == "worn brakes" %>
         <p> <strong>15 euros</strong> </p>
          <% elsif @repair.category == "broken chain" %>
         <p> <strong>20 euros</strong> </p>
          <% end %>
           <p><%= link_to "All about you", account_path %></p>
           <p><%= link_to "Add a review about your saver", users_path %></p>
          <div class ="list inline">
            <%= link_to "Cancel your demand", repair_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-brand" %> <br></br><%= link_to "Modify your informations", edit_repair_path(@repair), class: "btn btn-brand" %>
        </div>
      </div>
      <br></br>
      <br></br>

      <div class= "row">
      <% if @repair.photo %>
      <p><strong>The photo you sent to us: </strong> </p>
      <%= cl_image_tag @repair.photo.path, width: 350, height: 250, crop: :fill %>
      <% end %>
      <% if @repair.description.present? %>
      <p> <strong>The message you sent</strong> </p>
      <%= @repair.description %>
      <% end %>
      </div>

      </div>
    </div>
<!-- displaying the address of the repair and the map -->
    <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-5 col-md-offset-1">
      <div class="" style="text-align: justify;">
        <h3>This is our meeting point</h3>
        <strong><address style="margin-bottom: 10px;">
              <%= @repair.address %>
              </address></strong>
        <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=450x380&sensor=false&maptype=roadmap&markers=color:orange|#{@repair.address}" %>
        <br></br>
        <br></br>
      </div>
    </div>
  </div>
</div>



<% content_for(:after_js) do %>
  <script>

  var pusher = new Pusher('2d2714db74c5bdaeee36', {
      cluster: 'eu',
      encrypted: true
    });

    var channel = pusher.subscribe("repair-<%= @repair.id %>");
    console.log(channel);
    channel.bind('my_event', function(data) {
      $('#repair_man').text(data.repair_man +' is coming!');
    });
  </script>
<% end %>

app/views/repairs/update.html.erb
<h1>Repairs#update</h1>
<p>Find me in app/views/repairs/update.html.erb</p>